// <auto-generated />
using System;
using DriverDms.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DriverDms.Infrastructure.Migrations
{
    [DbContext(typeof(DriverDmsContext))]
    [Migration("20260709060000_AddDocumentPaths")]
    partial class AddDocumentPaths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DriverDms.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditLogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AuditLogId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.BloodGroup", b =>
                {
                    b.Property<int>("BloodGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BloodGroupId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BloodGroupId");

                    b.ToTable("BloodGroups");

                    b.HasData(
                        new
                        {
                            BloodGroupId = 1,
                            Name = "A+"
                        },
                        new
                        {
                            BloodGroupId = 2,
                            Name = "A-"
                        },
                        new
                        {
                            BloodGroupId = 3,
                            Name = "B+"
                        },
                        new
                        {
                            BloodGroupId = 4,
                            Name = "B-"
                        },
                        new
                        {
                            BloodGroupId = 5,
                            Name = "AB+"
                        },
                        new
                        {
                            BloodGroupId = 6,
                            Name = "AB-"
                        },
                        new
                        {
                            BloodGroupId = 7,
                            Name = "O+"
                        },
                        new
                        {
                            BloodGroupId = 8,
                            Name = "O-"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.CorrectiveAction", b =>
                {
                    b.Property<int>("CorrectiveActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CorrectiveActionId"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ActionTaken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("IncidentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("PenaltyTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("CorrectiveActionId");

                    b.HasIndex("IncidentId");

                    b.HasIndex("PenaltyTypeId");

                    b.ToTable("CorrectiveActions");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<string>("AadhaarLast4")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AadhaarNoEncrypted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BloodGroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("DriverCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DriverPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmergencyContactRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("BloodGroupId");

                    b.HasIndex("CurrentStatusId");

                    b.HasIndex("DriverCode")
                        .IsUnique();

                    b.HasIndex("Mobile");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.DriverStatusHistory", b =>
                {
                    b.Property<int>("StatusHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusHistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ChangedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("DriverStatusTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusHistoryId");

                    b.HasIndex("DriverId");

                    b.HasIndex("DriverStatusTypeId");

                    b.ToTable("DriverStatusHistories");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.DriverStatusType", b =>
                {
                    b.Property<int>("DriverStatusTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverStatusTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DriverStatusTypeId");

                    b.ToTable("DriverStatusTypes");

                    b.HasData(
                        new
                        {
                            DriverStatusTypeId = 1,
                            Name = "Active"
                        },
                        new
                        {
                            DriverStatusTypeId = 2,
                            Name = "Suspended"
                        },
                        new
                        {
                            DriverStatusTypeId = 3,
                            Name = "OnMedicalHold"
                        },
                        new
                        {
                            DriverStatusTypeId = 4,
                            Name = "Retired"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.DriverTransporterHistory", b =>
                {
                    b.Property<int>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignmentId"));

                    b.Property<DateTime>("AssignmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("TransporterId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("AssignmentId");

                    b.HasIndex("DriverId")
                        .IsUnique()
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("TransporterId");

                    b.ToTable("DriverTransporterHistories");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Endorsement", b =>
                {
                    b.Property<int>("EndorsementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EndorsementId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EndorsementId");

                    b.ToTable("Endorsements");

                    b.HasData(
                        new
                        {
                            EndorsementId = 1,
                            IsActive = true,
                            Name = "Hazmat"
                        },
                        new
                        {
                            EndorsementId = 2,
                            IsActive = true,
                            Name = "Passenger"
                        },
                        new
                        {
                            EndorsementId = 3,
                            IsActive = true,
                            Name = "Tanker"
                        },
                        new
                        {
                            EndorsementId = 4,
                            IsActive = true,
                            Name = "Air Brakes"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.FitnessStatus", b =>
                {
                    b.Property<int>("FitnessStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FitnessStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FitnessStatusId");

                    b.ToTable("FitnessStatuses");

                    b.HasData(
                        new
                        {
                            FitnessStatusId = 1,
                            Name = "Fit"
                        },
                        new
                        {
                            FitnessStatusId = 2,
                            Name = "Fit with remarks"
                        },
                        new
                        {
                            FitnessStatusId = 3,
                            Name = "Unfit"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.GateNumber", b =>
                {
                    b.Property<int>("GateNumberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GateNumberId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GateNumberId");

                    b.ToTable("GateNumbers");

                    b.HasData(
                        new
                        {
                            GateNumberId = 1,
                            Name = "Gate 1"
                        },
                        new
                        {
                            GateNumberId = 2,
                            Name = "Gate 2"
                        },
                        new
                        {
                            GateNumberId = 3,
                            Name = "Gate 3"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Incident", b =>
                {
                    b.Property<int>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentReportPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IncidentTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RootCauseCompleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SeverityLevelId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("IncidentId");

                    b.HasIndex("DriverId");

                    b.HasIndex("IncidentDate");

                    b.HasIndex("IncidentTypeId");

                    b.HasIndex("SeverityLevelId");

                    b.ToTable("Incidents");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.IncidentType", b =>
                {
                    b.Property<int>("IncidentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncidentTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncidentTypeId");

                    b.ToTable("IncidentTypes");

                    b.HasData(
                        new
                        {
                            IncidentTypeId = 1,
                            Name = "Incident"
                        },
                        new
                        {
                            IncidentTypeId = 2,
                            Name = "Near Miss"
                        },
                        new
                        {
                            IncidentTypeId = 3,
                            Name = "Violation"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.License", b =>
                {
                    b.Property<int>("LicenseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicenseId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicenceFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LicenseNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("datetime2");

                    b.Property<int>("VehicleTypeId")
                        .HasColumnType("int");

                    b.HasKey("LicenseId");

                    b.HasIndex("DriverId");

                    b.HasIndex("LicenseNo")
                        .IsUnique();

                    b.HasIndex("ValidTill");

                    b.HasIndex("VehicleTypeId");

                    b.ToTable("Licenses", t =>
                        {
                            t.HasCheckConstraint("CK_License_ValidTill", "[ValidTill] > [IssueDate]");
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.LicenseEndorsement", b =>
                {
                    b.Property<int>("LicenseId")
                        .HasColumnType("int");

                    b.Property<int>("EndorsementId")
                        .HasColumnType("int");

                    b.HasKey("LicenseId", "EndorsementId");

                    b.HasIndex("EndorsementId");

                    b.ToTable("LicenseEndorsements");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.MedicalRecord", b =>
                {
                    b.Property<int>("MedicalRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MedicalRecordId"));

                    b.Property<bool>("AlcoholTestPass")
                        .HasColumnType("bit");

                    b.Property<string>("BP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChronicIllness")
                        .HasColumnType("bit");

                    b.Property<string>("ChronicIllnessRemarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExamDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FitnessStatusId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalCertificatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidTill")
                        .HasColumnType("datetime2");

                    b.Property<bool>("VisionTestPass")
                        .HasColumnType("bit");

                    b.HasKey("MedicalRecordId");

                    b.HasIndex("DriverId");

                    b.HasIndex("FitnessStatusId");

                    b.HasIndex("ValidTill");

                    b.ToTable("MedicalRecords", t =>
                        {
                            t.HasCheckConstraint("CK_MedicalRecord_ValidTill", "[ValidTill] > [ExamDate]");
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DismissedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NotificationEntityTypeId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationEntityTypeId");

                    b.HasIndex("NotificationStatusId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.NotificationEntityType", b =>
                {
                    b.Property<int>("NotificationEntityTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationEntityTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationEntityTypeId");

                    b.ToTable("NotificationEntityTypes");

                    b.HasData(
                        new
                        {
                            NotificationEntityTypeId = 1,
                            Name = "License"
                        },
                        new
                        {
                            NotificationEntityTypeId = 2,
                            Name = "Medical"
                        },
                        new
                        {
                            NotificationEntityTypeId = 3,
                            Name = "Training"
                        },
                        new
                        {
                            NotificationEntityTypeId = 4,
                            Name = "Incident"
                        },
                        new
                        {
                            NotificationEntityTypeId = 5,
                            Name = "Document"
                        },
                        new
                        {
                            NotificationEntityTypeId = 6,
                            Name = "System"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.NotificationStatus", b =>
                {
                    b.Property<int>("NotificationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationStatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NotificationStatusId");

                    b.ToTable("NotificationStatuses");

                    b.HasData(
                        new
                        {
                            NotificationStatusId = 1,
                            Name = "Pending"
                        },
                        new
                        {
                            NotificationStatusId = 2,
                            Name = "Sent"
                        },
                        new
                        {
                            NotificationStatusId = 3,
                            Name = "Dismissed"
                        },
                        new
                        {
                            NotificationStatusId = 4,
                            Name = "Expired"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.PenaltyType", b =>
                {
                    b.Property<int>("PenaltyTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenaltyTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PenaltyTypeId");

                    b.ToTable("PenaltyTypes");

                    b.HasData(
                        new
                        {
                            PenaltyTypeId = 1,
                            Name = "Warning"
                        },
                        new
                        {
                            PenaltyTypeId = 2,
                            Name = "Suspension"
                        },
                        new
                        {
                            PenaltyTypeId = 3,
                            Name = "Retraining"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.PlantMovement", b =>
                {
                    b.Property<int>("MovementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovementId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfEntry")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfExit")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int?>("EntryAuthorizedBy")
                        .HasColumnType("int");

                    b.Property<int>("GateNumberId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PurposeTypeId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<string>("VehicleNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MovementId");

                    b.HasIndex("DateOfEntry");

                    b.HasIndex("DriverId");

                    b.HasIndex("GateNumberId");

                    b.HasIndex("PurposeTypeId");

                    b.HasIndex("VehicleNo");

                    b.ToTable("PlantMovements", t =>
                        {
                            t.HasCheckConstraint("CK_PlantMovement_DateOfExit", "[DateOfExit] IS NULL OR [DateOfExit] >= [DateOfEntry]");
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.PurposeType", b =>
                {
                    b.Property<int>("PurposeTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurposeTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PurposeTypeId");

                    b.ToTable("PurposeTypes");

                    b.HasData(
                        new
                        {
                            PurposeTypeId = 1,
                            Name = "Loading"
                        },
                        new
                        {
                            PurposeTypeId = 2,
                            Name = "Unloading"
                        },
                        new
                        {
                            PurposeTypeId = 3,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.SeverityLevel", b =>
                {
                    b.Property<int>("SeverityLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SeverityLevelId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SeverityLevelId");

                    b.ToTable("SeverityLevels");

                    b.HasData(
                        new
                        {
                            SeverityLevelId = 1,
                            Name = "Low"
                        },
                        new
                        {
                            SeverityLevelId = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            SeverityLevelId = 3,
                            Name = "High"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.SystemConfiguration", b =>
                {
                    b.Property<string>("ConfigKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConfigValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ConfigKey");

                    b.ToTable("SystemConfigurations");

                    b.HasData(
                        new
                        {
                            ConfigKey = "LicenseReminderDays",
                            ConfigValue = "30",
                            Description = "Days before License.ValidTill to raise a notification",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "MedicalReminderDays",
                            ConfigValue = "30",
                            Description = "Confirm actual value with client - Excel didn't specify one (design doc §5)",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ConfigKey = "TrainingReminderDays",
                            ConfigValue = "30",
                            Description = "Confirm actual value with client - Excel didn't specify one (design doc §5)",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCompleted")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrainerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrainingTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidUpto")
                        .HasColumnType("datetime2");

                    b.HasKey("TrainingId");

                    b.HasIndex("DriverId");

                    b.HasIndex("TrainingTypeId");

                    b.HasIndex("ValidUpto");

                    b.ToTable("Trainings", t =>
                        {
                            t.HasCheckConstraint("CK_Training_ValidUpto", "[ValidUpto] > [DateCompleted]");
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.TrainingType", b =>
                {
                    b.Property<int>("TrainingTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrainingTypeId");

                    b.ToTable("TrainingTypes");

                    b.HasData(
                        new
                        {
                            TrainingTypeId = 1,
                            Name = "Induction"
                        },
                        new
                        {
                            TrainingTypeId = 2,
                            Name = "Refresher"
                        },
                        new
                        {
                            TrainingTypeId = 3,
                            Name = "Defensive Driving"
                        },
                        new
                        {
                            TrainingTypeId = 4,
                            Name = "PEP Talk"
                        });
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Transporter", b =>
                {
                    b.Property<int>("TransporterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransporterId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AgreementValidTill")
                        .HasColumnType("datetime2");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DeletedBy")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("int");

                    b.HasKey("TransporterId");

                    b.ToTable("Transporters");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.VehicleType", b =>
                {
                    b.Property<int>("VehicleTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleTypeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VehicleTypeId");

                    b.ToTable("VehicleTypes");

                    b.HasData(
                        new
                        {
                            VehicleTypeId = 1,
                            IsActive = true,
                            Name = "LMV"
                        },
                        new
                        {
                            VehicleTypeId = 2,
                            IsActive = true,
                            Name = "HMV"
                        },
                        new
                        {
                            VehicleTypeId = 3,
                            IsActive = true,
                            Name = "Trailer"
                        },
                        new
                        {
                            VehicleTypeId = 4,
                            IsActive = true,
                            Name = "Tanker"
                        });
                });

            modelBuilder.Entity("DriverDms.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.CorrectiveAction", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Incident", "Incident")
                        .WithMany("CorrectiveActions")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.PenaltyType", "PenaltyType")
                        .WithMany()
                        .HasForeignKey("PenaltyTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Incident");

                    b.Navigation("PenaltyType");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Driver", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.BloodGroup", "BloodGroup")
                        .WithMany()
                        .HasForeignKey("BloodGroupId");

                    b.HasOne("DriverDms.Domain.Entities.DriverStatusType", "CurrentStatus")
                        .WithMany()
                        .HasForeignKey("CurrentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BloodGroup");

                    b.Navigation("CurrentStatus");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.DriverStatusHistory", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("StatusHistory")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.DriverStatusType", "DriverStatusType")
                        .WithMany()
                        .HasForeignKey("DriverStatusTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("DriverStatusType");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.DriverTransporterHistory", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("TransporterHistory")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.Transporter", "Transporter")
                        .WithMany("DriverAssignments")
                        .HasForeignKey("TransporterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Transporter");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Incident", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("Incidents")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.IncidentType", "IncidentType")
                        .WithMany()
                        .HasForeignKey("IncidentTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.SeverityLevel", "SeverityLevel")
                        .WithMany()
                        .HasForeignKey("SeverityLevelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("IncidentType");

                    b.Navigation("SeverityLevel");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.License", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("Licenses")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.VehicleType", "VehicleType")
                        .WithMany()
                        .HasForeignKey("VehicleTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("VehicleType");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.LicenseEndorsement", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Endorsement", "Endorsement")
                        .WithMany()
                        .HasForeignKey("EndorsementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.License", "License")
                        .WithMany("LicenseEndorsements")
                        .HasForeignKey("LicenseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Endorsement");

                    b.Navigation("License");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.MedicalRecord", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("MedicalRecords")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.FitnessStatus", "FitnessStatus")
                        .WithMany()
                        .HasForeignKey("FitnessStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("FitnessStatus");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Notification", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.NotificationEntityType", "NotificationEntityType")
                        .WithMany()
                        .HasForeignKey("NotificationEntityTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.NotificationStatus", "NotificationStatus")
                        .WithMany()
                        .HasForeignKey("NotificationStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NotificationEntityType");

                    b.Navigation("NotificationStatus");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.PlantMovement", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("PlantMovements")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.GateNumber", "GateNumber")
                        .WithMany()
                        .HasForeignKey("GateNumberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.PurposeType", "PurposeType")
                        .WithMany()
                        .HasForeignKey("PurposeTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("GateNumber");

                    b.Navigation("PurposeType");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Training", b =>
                {
                    b.HasOne("DriverDms.Domain.Entities.Driver", "Driver")
                        .WithMany("Trainings")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DriverDms.Domain.Entities.TrainingType", "TrainingType")
                        .WithMany()
                        .HasForeignKey("TrainingTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TrainingType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("DriverDms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("DriverDms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DriverDms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("DriverDms.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Driver", b =>
                {
                    b.Navigation("Incidents");

                    b.Navigation("Licenses");

                    b.Navigation("MedicalRecords");

                    b.Navigation("PlantMovements");

                    b.Navigation("StatusHistory");

                    b.Navigation("Trainings");

                    b.Navigation("TransporterHistory");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Incident", b =>
                {
                    b.Navigation("CorrectiveActions");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.License", b =>
                {
                    b.Navigation("LicenseEndorsements");
                });

            modelBuilder.Entity("DriverDms.Domain.Entities.Transporter", b =>
                {
                    b.Navigation("DriverAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
