export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/dashboard',
  DRIVERS: '/drivers',
  DRIVER_NEW: '/drivers/new',
  DRIVER_DETAILS: (id: string | number = ':id') => `/drivers/${id}`,
  DRIVER_EDIT: (id: string | number = ':id') => `/drivers/${id}/edit`,
  LICENSES: '/licenses',
  LICENSE_NEW: '/licenses/new',
  LICENSE_EDIT: (id: string | number = ':id') => `/licenses/${id}/edit`,
  MEDICAL: '/medical-records',
  MEDICAL_NEW: '/medical-records/new',
  MEDICAL_EDIT: (id: string | number = ':id') => `/medical-records/${id}/edit`,
  TRAININGS: '/trainings',
  TRAINING_NEW: '/trainings/new',
  TRAINING_EDIT: (id: string | number = ':id') => `/trainings/${id}/edit`,
  INCIDENTS: '/incidents',
  INCIDENT_NEW: '/incidents/new',
  INCIDENT_DETAILS: (id: string | number = ':id') => `/incidents/${id}`,
  INCIDENT_EDIT: (id: string | number = ':id') => `/incidents/${id}/edit`,
  PLANT_MOVEMENTS: '/plant-movements',
  PLANT_MOVEMENT_NEW: '/plant-movements/new',
  TRANSPORTERS: '/transporters',
  TRANSPORTER_NEW: '/transporters/new',
  TRANSPORTER_DETAILS: (id: string | number = ':id') => `/transporters/${id}`,
  TRANSPORTER_EDIT: (id: string | number = ':id') => `/transporters/${id}/edit`,
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
} as const;
